dist: trusty
sudo: required 

language: cpp
cache: ccache
  
install:
  - sudo apt update
  - sudo apt install mpi-default-bin mpi-default-dev
  - export PATH="$HOME/opt/bin:$PATH"
  - export LD_LIBRARY_PATH="$HOME/opt/lib:$LD_LIBRARY_PATH"
  - sudo ln -s ccache /usr/local/bin/mpic++
  - export PATH=/usr/lib/ccache:${PATH}
  - ccache -s
  - CXX="mpic++" .travis/install.plumed version=master
  - .travis/install.lammps version=pablo-fix
  - ccache -s

script:
  - ./run-tests.sh
# should add something that makes the script fail when there are errors
